jasmine-reporters version changed to 0.x.x
Recently a new version of jasmine-reporters (2.0.0) has been released which is incompatible with 0.x.x version. Due to version range ">=0.2.0" the latest version gets installed causing jasmine to fail. Following error can be observed:

{project-path}/node_modules/jasmine-node/lib/jasmine-node/reporter.js:336
  jasmineNode.TeamcityReporter.prototype = new jasmine.TeamcityReporter;
                                           ^
TypeError: undefined is not a function